angular.module('cms').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('partial/project/project.html',
    "<div class=col-md-12 ng-controller=ProjectCtrl><h1 ng-if=!isEdit>Create new project</h1><h1 ng-if=isEdit>Edit project</h1><div class=\"btn btn-md pull-right btn-danger\" ng-click=delete(model._id) ng-if=isEdit>Delete</div><div class=\"btn btn-md pull-right btn-warning\" ng-click=cancel()>Cancel</div><div class=\"btn btn-md pull-right btn-success\" ng-click=save() ng-if=!isEdit>Create</div><div class=\"btn btn-md pull-right btn-success\" ng-click=save() ng-if=isEdit>Save</div><br><br><h1><label>Title, description and cover</label></h1><br><label for=title>Title</label><input type=text id=title class=form-control ng-model=\"model.title\"><br><label for=description>Description</label><textarea id=description ui-tinymce ng-model=model.description class=form-control></textarea><br><label>Upload cover</label><br><div class=\"btn btn-primary\" ng-disabled=options.selectedFile ngf-select=selectFile($file)>Select cover</div><div class=\"btn btn-success\" ng-click=upload(options.selectedFile) ng-if=options.selectedFile>Upload cover</div><br><p>{{ options.selectedFile.name }}</p><br><div class=progress><div class=\"progress-bar progress-bar-success\" role=progressbar aria-valuenow=\"{{ options.progressPercentage }}\" aria-valuemin=0 aria-valuemax=100 style=\"width: {{ options.progressPercentage }}%\">{{ options.progressPercentage }}% Complete (success)</div></div><img id=cover-image ng-src=\"/assets/images/{{ model.coverImage.fileName }}\"><hr><h1><label>Sections</label></h1><br><div ng-repeat=\"section in sections\" id=section class=col-md-4><input type=text class=form-control ng-model=section.title><br><div class=\"btn btn-primary\" ngf-select=\"addSections($file, section)\">Upload {{ section.title }} image</div><div>Current {{ section.title }} image fileName: {{ section.image.fileName }}</div><br><img id=section-image ng-src=\"/assets/images/{{ section.image.fileName }}\"><br><br><div class=\"btn btn-danger\" ng-click=\"deleteSection(section, section._id)\">Delete this section</div><div class=\"btn btn-success\" ng-click=addSectionButton()>Add another section</div></div></div>"
  );


  $templateCache.put('partial/projects/projects.html',
    "<div class=\"col-md-12 projects-list\" ng-controller=ProjectsCtrl><h1>Projects List</h1><div class=\"btn btn-primary\" ng-click=createProject()>Create new</div><table class=\"table table-striped\"><thead><tr><th>Title</th><th ng-click=toggleDateOrder()>Date</th><th>Actions</th></tr></thead><tbody><tr ng-repeat=\"project in list | orderBy:options.orderFilter\"><td>{{ project.title }}</td><td>{{ project.date | date:'dd/MM/yy hh:mm:ss' }}</td><td><div class=\"btn btn-xs btn-danger\" ng-click=deleteProject(project._id)>Delete</div><div class=\"btn btn-xs btn-primary\" ui-sref=project({id:project._id})>Edit</div></td></tr></tbody></table></div>"
  );

}]);
